import Header from "./components/header";
import Footer from "./components/footer";
import "./globals.css";
import { Syne } from "next/font/google";

const inter = Syne({ subsets: ["latin"] });

export const metadata = {
	title: "Swanky - Serverside opgave",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
